name: Fraud Workflow
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
       runs-on: ubuntu-latest
       steps:
        - name: Check Codes 
          run: actions/checkout@v4
        - name: Load Python
          run: actions/setup-python@v5
        - name: Install Dependencies
          run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
        - name: Look at the basic Syntax
          run: python -m py_compile app.py
        - name: Run Tests
          run: |
           pytest -q
          


