name : Fraud CI
on:
    push:
        branches: [main]
    pull_request:
        branches : [main]

jobs:
    build:
        runs-on : ubuntu-latest
        steps:
           - name: Check code
             uses: actions/checkout@v4
           - name: Load python
             uses : actions/setup-python@v5
             with:
                python-version: '3.12'
           - name: Install Dependancies
             run: python -m pip install --upgrade pip
                  pip install -r requirments.txt
           - name: Look at basic syntax
             run : python -m py-compile app.py
           - name : Run Tests
             run : pytest -q
        


    